---
title: "R_rancimat"
output: html_document
---

```{r}
install.packages("tidyverse")
library(tidyverse)
```

```{r}
Ranciamt_data <- read.csv(file = '/Users/ooowen/Desktop/Lab_Data/Rancimat_Data_2021.csv')
Ranciamt_data
remove_NA <- Ranciamt_data [!(Ranciamt_data$Induction.Time..h.=="N/A"),] ## remove all the N/A

```

```{r}
remove_NA$Induction.Time..h. <- as.numeric(remove_NA$Induction.Time..h.) 
filtered.Induction.T <- na.omit(remove_NA)
filtered.Induction.T

Ave_induction_time <- mean(filtered.Induction.T$Induction.Time..h.) 
Ave_induction_time

```
```{r}
median_induction_time <- median(filtered.Induction.T$Induction.Time..h.)
median_induction_time
```

```{r}
sd_induction_time <- sd(filtered.Induction.T$Induction.Time..h., na.rm = TRUE)
sd_induction_time
```
```{r}
y <- dnorm(filtered.Induction.T$Induction.Time..h., mean = Ave_induction_time, sd = sd_induction_time)

plot(filtered.Induction.T$Induction.Time..h., y )
```

```{r}
t.test(filtered.Induction.T$Induction.Time..h., mu = 5)

```
```{r}
greater.than.mean <- filter(filtered.Induction.T, Induction.Time..h. >=  Ave_induction_time)
greater.than.mean <- as.data.frame(greater.than.mean)
```


